### ISSUE TITLE
Create a test server which simply returns canned responses

### ISSUE THREAD

**Issue by CloCkWeRX** [TheThingSystem/node-samsung-airconditioner#1]

**Comment by CloCkWeRX** [comment]
:/ Node hurts my depenency injection focused testing brain.

I more or less just want to do a fake, in memory socket - and emit that I have 'new data' every now and then.

I'd normally just inject a premade tls.connect into the constructor and swap it out there, with something that does this like of conversation:

### Failed auth

```
  var test = {
    messages: [
      'DRC-1.00' + "\r\n",
      '<?xml version="1.0" encoding="utf-8" ?><Update Type="InvalidateAccount"/>' + "\r\n"
    ],
    read: function() { return test.messages.shift;  },
    write: function(line) {
      if (line == '<Request Type="GetToken" />' + "\r\n") {
        messages.push('<?xml version="1.0" encoding="utf-8" ?><Response Type="GetToken" Status="Ready"/>' + "\r\n");

        setTimeout(function() {
          messages.push('<?xml version="1.0" encoding="utf-8" ?><Response Status="Fail" Type="Authenticate" ErrorCode="301" />' + "\r\n");
        }, 30000);

      }
    }
```

### successful auth

```
  var test = {
    messages: [
      'DRC-1.00' + "\r\n",
      '<?xml version="1.0" encoding="utf-8" ?><Update Type="InvalidateAccount"/>' + "\r\n"
    ],
    read: function() { return test.messages.shift;  },
    write: function(line) {
      if (line == '<Request Type="GetToken" />' + "\r\n") {
        messages.push('<?xml version="1.0" encoding="utf-8" ?><Response Type="GetToken" Status="Ready"/>' + "\r\n");

        setTimeout(function() {
          messages.push('<?xml version="1.0" encoding="utf-8" ?><Response Status="Success" Type="Authenticate" Token="12345" />' + "\r\n");
        }, 10000);

      }
    }
```

**Comment by mrose17** [comment]
just so that i'm on the same page: you'd like a node program that you can run that pretends to be a samsung smart air conditioner (e.g., responds to SSDP, and XML/TLS like the real deal)?

**Comment by CloCkWeRX** [comment]
In the interests of KISS, no, that wasn't my first intent. 

An in memory fake of just the XML communication should be a lot easier - a socket connection tends to be not much more than read/write from a buffer; and at the end of the day you end up with something like https://github.com/vcr/vcr - a bunch of conversations pre-recorded, allowing you to test the important stuff (when I see X, respond with Y).

Unfortunately due to the refactoring we no longer have testing seams as easily available. 

Ruby version
https://bitbucket.org/CloCkWeRX/samsung-remote/src/20efc6ea8fe093070673f6b49d5b77dced7658c8/example-direct.rb?at=master

Want a different connection?

```
Samsung::Factory.an_ssl_client(config)
```

can just become something like: https://gist.github.com/earlonrails/1470076

That's part of the reason I had a distinct authenticator class, and distinct connection class originally - it was a lot easier to seperate the "wiring up" and "do communication" parts.

**Comment by mrose17** [comment]
OBE (overtaken by events)
